### ISSUE TITLE
Use logstream on my own machin

### ISSUE THREAD

**Issue by fallais** [acquia/logstream#19]
Hello,

I need to use `logstream` on my own machin, I mean, not on the Acquia cloud instance. That being said, I tried and I face issues with `drush` and `logstream` itself.

How do I proceed ?

Step 1 : get the aliases from Acquia admin page.
Step 2 : install logstream
Step 3 : trying to use `drush ac-site-list` : not working because `drush` is not installed. I install it (version 8).
Step 4 : trying to use `drush ac-site-list` : not working `Call to undefined curl_init() in /root/.drush/acapi.drush.inc:1109`

My machin is an Ubuntu 16.04.
Could you please help ?

**Comment by Zlender** [comment]
Hi @fallais can you try latest master. We have switch logstream gem to use Acquia CloudAPI v2 and there is no dependency on Drush anymore.
